### ISSUE TITLE
The %v% doesn't work.

### ISSUE THREAD

**Issue by DolapoA** [jokergoo/ComplexHeatmap-reference#3]
When I try to vertically concatenate heatmaps using the `%v%` I get the following error:
Error in hm %v% hm2 : could not find function "%v%"

` 
#### create heatmap
hm = Heatmap(matriXX,
	cluster_rows = FALSE,
	cluster_columns = hclust,
	col=colours,
	top_annotation=anno1,
	bottom_annotation=anno2,
heatmap_legend_param = list(title = "BlahBlah", color_bar = "continuous", legend_direction = "horizontal",
    legend_width = unit(5, "cm"), title_position = "lefttop")
	)

#### create heatmap
hm2 = Heatmap(matriXX,
	cluster_columns = hclust,
	col=colours2,
	top_annotation=anno1,
	bottom_annotation=anno2,
heatmap_legend_param = list(title = "BlahBlah2", color_bar = "continuous", legend_direction = "horizontal",
    legend_width = unit(5, "cm"), title_position = "lefttop")
	)
hm_list <- hm %v% hm2
#### draw the heatmap, specifying legend locations
draw(hm_list,heatmap_legend_side = "bottom", annotation_legend_side = "bottom")`

I was wondering how I can get this to work.

**Comment by jokergoo** [comment]
You need to update the package:

```r
library(devtools)
install_github("jokergoo/ComplexHeatmap")
```

**Comment by DolapoA** [comment]
Thanks I'll try this.
